// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnfldginvpnpljskzmmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZmxkZ2ludnBucGxqc2t6bW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTQ5NjksImV4cCI6MjA1ODk3MDk2OX0.MchMhh1zj7fNxkEiH767nnwrwCj4oqfoMOC-A0_C-0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);